### PR TITLE
Vulnerability update

### PR DESCRIPTION
**Pull request by jaddison-ch**
### Change description

- Update Spring boot to latest version
- Implement the new vulnerability suppression method
- Make sure the Jib plugin docker images are correct

### Work checklist

* [ ] Bug fix
* [ ] New feature
* [ ] Breaking change

### Pull request checklist

* [X] I have added unit tests for new code that I have added
* [X] I have added/updated functional tests where appropriate
* [X] The code follows our [coding standards](https://github.com/companieshouse/styleguides/blob/master/java.md)

__An exhaustive list of peer review checks can be read [here](https://github.com/companieshouse/styleguides/blob/master/java_review.md#developer-actions-prior-to-code-commitreview-started)__

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by foman-ch — APPROVED** [review]

**Pull request merged**
