### PR TITLE
Tech debt

### PR DESCRIPTION
**Pull request by tmoller-ch**
### Change description
Update TF modules and tag

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by rhilgenbergbastos-ch — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Pull request merged**
